# Generated by Django 6.0.7 on 2026-07-27 17:38

import apps.accounts.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('pais', models.CharField(max_length=100)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('provider', models.CharField(choices=[('local', 'Local'), ('google', 'Google')], default='local', max_length=10)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo')], default='pendiente', max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['-creado_en'],
            },
            managers=[
                ('objects', apps.accounts.managers.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='CodigoOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('tipo', models.CharField(choices=[('registro', 'Registro'), ('reset_password', 'Reset de password')], max_length=20)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('intentos', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codigos_otp',
                'ordering': ['-creado_en'],
            },
        ),
    ]
