# Generated by Django 6.0.7 on 2026-08-04 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='meta_racha_semanal',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dias por semana que el usuario se propone correr, para mantener su racha.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
