# Generated by Django 6.0.7 on 2026-07-27 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('distancia_km', models.DecimalField(decimal_places=3, max_digits=6)),
                ('duracion_seg', models.PositiveIntegerField()),
                ('ritmo_seg_km', models.PositiveIntegerField(editable=False)),
                ('calorias', models.PositiveIntegerField(editable=False)),
                ('ruta_geojson', models.JSONField(blank=True, default=list)),
                ('elevacion_m', models.IntegerField(blank=True, null=True)),
                ('iniciada_en', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carreras',
                'ordering': ['-iniciada_en'],
            },
        ),
    ]
