# Generated by Django 6.0.7 on 2026-07-28 18:02

from django.db import migrations

PAISES = [
    ('BZ', 'Belice'),
    ('CR', 'Costa Rica'),
    ('SV', 'El Salvador'),
    ('GT', 'Guatemala'),
    ('HN', 'Honduras'),
    ('NI', 'Nicaragua'),
    ('PA', 'Panama'),
    ('MX', 'Mexico'),
    ('CO', 'Colombia'),
    ('US', 'Estados Unidos'),
]


def crear_paises(apps, schema_editor):
    Pais = apps.get_model('common', 'Pais')
    for codigo, nombre in PAISES:
        Pais.objects.get_or_create(codigo=codigo, defaults={'nombre': nombre})


def eliminar_paises(apps, schema_editor):
    Pais = apps.get_model('common', 'Pais')
    Pais.objects.filter(codigo__in=[codigo for codigo, _ in PAISES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_paises, eliminar_paises),
    ]
