# Generated by Django 6.0.7 on 2026-07-27 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada')], default='aceptada', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('amigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_recibidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_iniciadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'amistades',
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'amigo'), name='amistad_unica_por_par')],
            },
        ),
    ]
